[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gymnasium.mbt"
version = "0.0.1"
dependencies = [
  "gymnasium[all]",
  "wasmtime",
]

[tool.setuptools.packages.find]
where = ["src"]
